#!/usr/bin/env python3
"""Simple greeting script to demonstrate Python support."""

import sys

def main() -> None:
    name = sys.argv[1] if len(sys.argv) > 1 else "friend"
    print(f"Hello, {name}! This greeting was generated by Python.")


if __name__ == "__main__":
    main()
